### PR TITLE
Upgrade to Junit 4.13

### PR DESCRIPTION
**Pull request by weiminyu**
Removed the third_party module and all usage of
JunitBackPort. replacing them with Assert.assertThrows.

---
This change is [Reviewable](https://reviewable.io/reviews/google/java-monitoring-client-library/15)

### CODE REVIEW

**Review by hstonec — COMMENTED** [review]
quick question, does this totally remove Junit 4.12 from our dependencies? I have been having dependency issue in Intellij after merging the junit upgrade. The symptom is that `Assert.assertThrow` cannot be found as Intellij uses `Assert` from 4.12 instead of 4.13, I guess it is because both versions exist in the classpath and it depends which one is loaded first. BTW, I can still build the project from command line, it is just Intellij having this problem.

> *[Reviewable](https://reviewable.io/reviews/google/java-monitoring-client-library/15#-:-Ly_d53NEh0LlOwhJbxg:b-p64tgw)* status: 0 of 22 files reviewed, all discussions resolved (waiting on @jianglai)

**Comment by jianglai** [comment]
> quick question, does this totally remove Junit 4.12 from our dependencies? I have been having dependency issue in Intellij after merging the junit upgrade. The symptom is that `Assert.assertThrow` cannot be found as Intellij uses `Assert` from 4.12 instead of 4.13, I guess it is because both versions exist in the classpath and it depends which one is loaded first. BTW, I can still build the project from command line, it is just Intellij having this problem.
> 
> > _[Reviewable](https://reviewable.io/reviews/google/java-monitoring-client-library/15#-:-Ly_d53NEh0LlOwhJbxg:b-p64tgw)_ status: 0 of 22 files reviewed, all discussions resolved (waiting on @jianglai)

It should, unless we have other dependencies on 4.12.

**Review by weiminyu — COMMENTED** [review]
Try reimport the mvn project in Intellij, even if you have auto-import on.

> *[Reviewable](https://reviewable.io/reviews/google/java-monitoring-client-library/15#-:-Ly_n6Ro9fnGRkf1FafC:b-opqsep)* status: 0 of 22 files reviewed, all discussions resolved (waiting on @jianglai)

**Review by jianglai — APPROVED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/java-monitoring-client-library/15)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
